# This is common Secret to store the username and password sensitive information externally as practice, and normally this file only known by K8S, not into git repo. to share to others.
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
# Opaque - key value pair type
type: Opaque
data:
# The secret username password in this practice sharely used by MongoDB and MongoExpress
  # echo -n 'yourUserName' | base64
  mongo-root-username: dXNlcm5hbWU=
  # echo -n 'yourPassword' | base64
  mongo-root-password: cGFzc3dvcmQ=

# kubectl apply -f 1-1-mongo-secret.yaml
# kubectl get secret